elastic-query-service:
  version: v1
  custom-audience: elastic-query-service

server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/microservices-realm
          # for loading public key in order to validate what's signed by the private key.
          jwk-set-uri: http://localhost:8081/auth/realms/microservices-realm/protocol/openid-connect/certs

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

# Normally these information should come from a persistent store or LDAP
# But just for simplicity here we add these from the configuration file.
user-config:
  username: test
  password: '{cipher}c9f92fb46a46ef237e51c5d3af40d6c110ca8b0e71706bf23ff11c49b0038f0c'
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  # There is no wildcard in this path, so sub-paths of /api-docs are still security-guarded.
  paths-to-ignore: /api-docs