version: '3.7'
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - "8081:8081"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      # Run the service and use it from http://localhost:8081/auth/
      - "JAVA_OPTS=-Djboss.http.port=8081"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=host.docker.internal"
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_SCHEMA=keycloak"
      - "DB_PASSWORD=keycloak"

# The schema relating to our configuration can be simplified as:
# Client ---< Scope ---< Role >--- Group ---< User
# Though, client can directly have many roles without going through scopes
# also users can have many roles without going through groups.

# To use user-password mode to obtain an access token when web client isn't developed yet:
#  curl -X POST -d 'grant_type=password&username=app_user&password=app_user&client_it_secret=94886fc2-fa40-4ab0-ac8f-5db365fabe0e' http://localhost:8081/auth/realms/microservices-realm/protocol/openid-connect/token