server:
  port: 8761

spring:
  application:
    name: eureka-discovery-service

eureka:
  client:
    # To avoid this service registering itself for single service use-case.
    # Because when there is no peer, we get an error.
    register-with-eureka: false
    # For a single server case, no need to fetch other registries.
    fetch-registry: false
  instance:
    appname: service-registry-cluster

logging:
  level:
    ROOT: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

log:
  app-name: discovery-service

